### ISSUE TITLE
Why don't pine trees use pine trunks?

### ISSUE THREAD

**Issue by HybridDog** [Splizard/minetest-mod-snow#10]

**Comment by Splizard** [comment]
If someone makes a pull request, I'll merge.
Just noting that snow mod seems to be becoming more obsolete with the new biome system and with most of the blocks now present in default.

**Comment by HybridDog** [comment]
l'm asking because my swamp mod removes default tree nodes but not pines (l want to keep this common usual forest away from the swamp.)
![screenshot, come!](http://i.imgur.com/ggBi5Br.png)

As far as l know, the biome system doesn't work for mgv6.
l use mgv6 because it has very interesting caves and good looking cliffs.
The caves of mgv7 look good, too, but l think they're different, and so l would miss the other ones.
And the cliffs of mgv7 are only steep slopes.

**Comment by HybridDog** [comment]
l've got another question…
http://dev.minetest.net/minetest.override_item wrote "[minetest.override_item is] Available in 0.4.10+"
this function is used at https://github.com/Splizard/minetest-mod-snow/blob/master/src/nodes.lua#L314
The readme says "Minetest version:  0.4.9".
Does the snow mod work for minetest 0.4.9?

**Comment by Splizard** [comment]
hmmm probablly not, that is something worth updating, thanks
