### ISSUE TITLE
Sled reported not to be working

### ISSUE THREAD

**Issue by Splizard** [Splizard/minetest-mod-snow#13]
Minetestforfun reported this on the forums:
>The Sled doesn't work for me, can you check it please ? :)
>(i would create a event with it :p)

**Comment by HybridDog** [comment]
as far as l know it never worked

**Comment by Splizard** [comment]
It was working when I made them in version 2.0 (http://splizard.com/minetest/mods/snow-biomes/snow-2.0.zip)
hmmm... has there been changes to the api?

**Comment by Splizard** [comment]
Should be fixed now 61a4aeda611cbb07d038ee478c0fd59780215092
