### ISSUE TITLE
snow incompatible with technic_worldgen

### ISSUE THREAD

**Issue by asl97** [Splizard/minetest-mod-snow#14]
when technic_worldgen is enable along with snow,  the snow biome doesn't generate.

```
1. create new world (v6) with only snow enable
2. find spot with snow (preferably ice sheet)
3. quit to menu
4a. delete map.sqlite
4b. enter the world to make sure it still generate the snow (optional)
4c. delete map.sqlite (if 4b)
5. enable technic_worldgen only (it depend on default only)
6. enter world
7. snow doesn't generate
8. delete map.sqlite
9. disable technic_worldgen
10. enter world
11. snow generate
```

**Comment by HybridDog** [comment]
which mapgen version?

**Comment by asl97** [comment]
v6

**Comment by HybridDog** [comment]
strange…
when l enable moreblocks it works again

**Comment by asl97** [comment]
enabling moreblocks doesn't do anything for me but i did notice that making snow load after technic_worldgen does work

although i don't know if the ores from the worldgen still exist though

**Comment by HybridDog** [comment]
maybe somewhere is a depends.txt problem, e.g. two mods depending on each other

**Comment by asl97** [comment]
this seem more like the snow + plantlib problem

**Comment by asl97** [comment]
now it's just a matter of waiting for someone to push https://github.com/minetest-technic/technic/pull/229

**Comment by HybridDog** [comment]
l don't think that this is the problem
https://github.com/HybridDog/sumpf/blob/master/sumpf/mapgen.lua#L214

**Comment by asl97** [comment]
it works when i put it the same as what is use in the v6 though
https://github.com/Splizard/minetest-mod-snow/blob/master/src/mapgen_v6.lua#L91

**Comment by HybridDog** [comment]
l think if vm:read_from_map is used for emin and emax the area is not complete because else emin and emax expand 16 nodes further. And l think @paramat knows more about this.
Does it work if emin and emax of minetest.get_voxel_manip() is used in mapgen_v6.lua?

**Comment by asl97** [comment]
i tried putting some print before https://github.com/HybridDog/sumpf/blob/master/sumpf/mapgen.lua#L214 and notice that it doesn't always enter it.

i really thought putting `sumpf.always_generate = true` would stop it from working but it didn't

this is weird...

also, what do you mean by `Does it work if emin and emax of minetest.get_voxel_manip() is used in mapgen_v6.lua?`?

**Comment by HybridDog** [comment]
>i really thought putting sumpf.always_generate = true would stop it from working but it didn't

https://github.com/HybridDog/sumpf/blob/master/sumpf/mapgen.lua#L154
swamps are generated only in specific heights

>also, what do you mean by Does […]

l mean doing it the other way round, changing mapgen_v6.lua instead of oregen.lua

**Comment by asl97** [comment]
it seem to work, but it still is weird.

why does snow work with sumpf and not technic_worldgen even after commenting out the height filter?

**Comment by HybridDog** [comment]
ldk, it might have something to do with the order the minetest.register_on_generated are called

**Comment by HybridDog** [comment]
maybe minetest.get_mapgen_object needs to be used for the snow mod that calc_lighting works

**Comment by HybridDog** [comment]
ok, using the mapgen voxelmanip object fixes the problem l think
@asl97 thanks a lot for reporting the bug
