### ISSUE TITLE
Snow fall 

### ISSUE THREAD

**Issue by 00c** [Splizard/minetest-mod-snow#16]
Snow fall appear and cause lag cpu spike, ignores `snow_enable_snowfall = false` in my config, 
When i type /snow snow fall is unmarked, on restart snow fall stops, but something trigger it sometimes.
i add `snow_debug = true`  for now

**Comment by 00c** [comment]
Hi, logs are full of this, after i enable debug, is this snow fall?
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: p=(-19,0,83) allow_generate=0
> 2016-04-28 20:24:44: INFO[Emerge-0]: 
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: p=(-19,0,85) allow_generate=0
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: p=(-19,1,85) allow_generate=0
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: p=(-20,0,87) allow_generate=0EmergeThread: p=(-21,0,87) allow_generate=0
> 2016-04-28 20:24:44: INFO[Emerge-0]: 
> 2016-04-28 20:24:44: INFO[Emerge-1]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:44: INFO[Emerge-0]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:45: INFO[Emerge-0]: EmergeThread: p=(-16,0,86) allow_generate=EmergeThread: p=(0-16,0,87) allow_generate=0
> 2016-04-28 20:24:45: INFO[Emerge-1]: 
> 2016-04-28 20:24:45: INFO[Emerge-0]: EmergeThread: not in memory, attempting to load from disk
> 2016-04-28 20:24:45: INFO[Emerge-0]: EmergeThread: p=(-16,-1,85) allow_generate=0
> 2016-04-28 20:24:45: INFO[Emerge-1]: EmergeThread: not in memory, attempting to load from disk

**Comment by HybridDog** [comment]
l think the log doesn't show something about falling snow.
You don't use other mods adding weather, do you?

https://github.com/Splizard/minetest-mod-snow/blob/master/src/falling_snow.lua#L193
If you add ```print("snow may fall")``` there, every time snow may fall the message should be printed.

**Comment by 00c** [comment]
There is no other mod with weather as long i know.
How can i check to be sure?

**Comment by HybridDog** [comment]
Just put following code at the beginning of an init.lua of some mod:
```
local picle = minetest.add_particle
function minetest.add_particle(t, ...)
	print(minetest.get_last_run_mod() .. " mod adds particle: "..dump(t))
	return picle(t, ...)
end

local picspwn = minetest.add_particlespawner
function minetest.add_particlespawner(t, ...)
	print(minetest.get_last_run_mod() .. " mod adds particlespawner: "..dump(t))
	return picspwn(t, ...)
end
```
It overrides the particle and particlespawner spawn function to make them additionally print the mod which executes the function and the particledef, which contains the texture, which usually also has the mod name in it.
Please tell me the result and thanks for your patience.

For example after using the rocket launcher following gets printed:
```
2016-04-29 16:51:23: WARNING[Server]: The use of vel is deprecated. Use velocity instead
2016-04-29 16:51:23: WARNING[Server]: The use of acc is deprecated. Use acceleration instead
2016-04-29 16:51:31: ACTION[Server]: singleplayer uses nuke:rocket_launcher, pointing at [nothing]
nuke mod adds particle: {
	vel = {
		y = 0.75824815034866,
		x = -0.58162754774094,
		z = -0.29456606507301
	},
	pos = {
		y = 25.125,
		x = 354.88998413086,
		z = -488.40698242188
	},
	size = 1,
	expirationtime = 1.3517531007662,
	acc = {
		y = 75.824815034866,
		x = -58.162754774094,
		z = -29.456606507301
	},
	collisiondetection = false,
	texture = "nuke_rocket_launcher_back.png^[transform1"
}
```

**Comment by 00c** [comment]
done, i see many 

> homedecor mod adds particlespawner: {
> 	minacc = {
> 		y = -0,
> 		x = 0,
> 		z = -0
> 	},
> 	maxpos = {
> 		y = 17.65,
> 		x = -962.15,
> 		z = 1143.725
> 	},
> 	texture = "homedecor_steam.png",
> 	minpos = {
> 		y = 17.65,
> 		x = -962.15,
> 		z = 1143.725
> 	},
> 	minsize = 1,
> 	maxacc = {
> 		y = 0.003,
> 		x = 0,
> 		z = -0
> 	},
> 	amount = 1,
> 	minvel = {
> 		y = 0.01,
> 		x = -0.003,
> 		z = -0.003
> 	},
> 	minexptime = 2,
> 	maxexptime = 5,
> 	maxvel = {
> 		y = 0.01,
> 		x = 0.003,
> 		z = -0.003
> 	},
> 	time = 1,
> 	collisiondetection = false,
> 	maxsize = 1.2
> }

**Comment by HybridDog** [comment]
This obviously is steam from homedecor, which informations do you get about the snow particles?

**Comment by 00c** [comment]
Nothing, i let it run will check logs later, that is all i could find with snow

> 2016-04-29 17:53:08: INFO[Main]:   [snow        ] ["/home/mt/bin/../mods/snow/init.lua"]
> 17:53:08: WARNING: Undeclared global variable "drop" accessed at /home/mt/bin/../mods/snow/src/stairsplus.lua:274

how line 193 should look just ` print("snow may fall")`  ?

**Comment by HybridDog** [comment]
l don't use stairsplus

**Comment by 00c** [comment]
Looks as its fixed
