### ISSUE TITLE
huge snow areas

### ISSUE THREAD

**Issue by 00c** [Splizard/minetest-mod-snow#18]
Mapgen create huge areas with snow height is 1 node. It appear only underground

**Comment by HybridDog** [comment]
please show screenshots

**Comment by 00c** [comment]
http://imgur.com/5V127ph its 1 node

**Comment by HybridDog** [comment]
thanks a lot for reporting this bug, it should be fixed now

**Comment by 00c** [comment]
Thank you for fixing
