### ISSUE TITLE
Snow fall bug

### ISSUE THREAD

**Issue by 00c** [Splizard/minetest-mod-snow#19]
i have set in my config snow_enable_snowfall = false still it snows, cause high cpu usage server freezes for 30 sec sometimes longer then lag is gone.

**Comment by 00c** [comment]
When snowfall stops lag is gone.

**Comment by HybridDog** [comment]
l don't know how to reproduce this, you don't [use another](https://github.com/Splizard/minetest-mod-snow/issues/16#issuecomment-215745152) weather mod, do you?

**Comment by 00c** [comment]
i can't find in logs anything that trigger it.
Server starts player enter area it snows. 

> ACTION[Server]:  places node default:snow at (2524,28,-3224)

logs are full of it. Happen rarely but would like to know what trigger it. 
Maybe there are options to reduce cpu load on server side when it snows?
I was wondering if mapgen could cause snowfall.

**Comment by HybridDog** [comment]
>Maybe there are options to reduce cpu load on server side when it snows?

l thought the lag happens only client side.

>logs are full of it.

l assume this happens because minetest.place_node is used to put the snow and not minetest.set_node

**Comment by 00c** [comment]
After update to recent minetest dev server, snow keeps falling on all high areas. 
/snow command does not work either
> snow_enable_snowfall = false

**Comment by 00c** [comment]
Maybe it has to do with following error

> : [snow] falling_snow: step function set to calc_snowfall

**Comment by HybridDog** [comment]
That shouldn't be an error, it's an "info" log, it is shown when snowfall is enabled.
l don't know why you experience snowfall on all high areas, perlin noise (with x and z as arguments) is used to detect whether snow should be falling.

**Comment by Splizard** [comment]
This is resolved, the snowfall has been replaced with snowdrift snowfall and it can be enabled/disabled properly in the advanced settings of minetest.
