### ISSUE TITLE
Can't throw snowballs

### ISSUE THREAD

**Issue by jtrent238** [Splizard/minetest-mod-snow#33]
I can't Throw snowballs!

**Comment by HybridDog** [comment]
You throw them with left click.

**Comment by jtrent238** [comment]
Is it known to conflict with other mods, or does it only works on certain versions?

**Comment by jtrent238** [comment]
[gif](gif)

**Comment by jtrent238** [comment]
Nevermind I got it lol, Must have been pressing right click lol.
![image](https://puu.sh/zpiBa/1b34a4a58b.gif)
