### ISSUE TITLE
Snowballs can be used to erase panels on protected areas

### ISSUE THREAD

**Issue by eric-presbitero** [Splizard/minetest-mod-snow#38]
If you place a snowball behind a panel you will erase it.
This is also true for protected areas where you can't edit panels.

**Comment by HybridDog** [comment]
What exactly do you mean by placing a snowball behind a panel? 
![screenshot_20180504_195253](https://user-images.githubusercontent.com/3192173/39643375-d5ccfdb0-4fd4-11e8-85ee-e66dc2b9024c.png)

**Comment by HybridDog** [comment]
Those are not default signs, which mod do you use?

**Comment by eric-presbitero** [comment]
The mod is signs_lib

https://forum.minetest.net/viewtopic.php?f=11&t=13762

**Comment by HybridDog** [comment]
I can't reproduce the problem. If I right-click the node behind the sign, nothing happens:
![screenshot_20180505_164711](https://user-images.githubusercontent.com/3192173/39664502-322784ea-5084-11e8-937d-98fb8edccd63.jpg)

**Comment by eric-presbitero** [comment]
There is nothing more to it than that. the right click should work.
I noticed it in a public server "fozland". I will forward this post to the admins, the problem must be somewhere else.

Thanks for your time testing
