### ISSUE TITLE
attempt to index local 'node' (a nil value) in init.lua

### ISSUE THREAD

**Issue by heavygale** [Splizard/minetest-mod-snow#6]
I just got the following error:
>13:29:04: ERROR[main]: ERROR: An unhandled exception occurred: [/home/minetest/bin/../mods/snow/init.lua:91](https://github.com/Splizard/minetest-mod-snow/blob/master/init.lua#L91): attempt to index local 'node' (a nil value)
>13:29:04: ERROR[main]: stack traceback:
>13:29:04: ERROR[main]: [/home/minetest/bin/../mods/snow/init.lua:91](https://github.com/Splizard/minetest-mod-snow/blob/master/init.lua#L91): in function 'place'
13:29:04: ERROR[main]: [/home/minetest/bin/../mods/landrush/snow.lua:20](https://github.com/Bremaweb/landrush/blob/master/snow.lua#L20): in function <[/home/minetest/bin/../mods/landrush/snow.lua:12](https://github.com/Bremaweb/landrush/blob/master/snow.lua#L12)>

This may be a bug in landrush, but the snow mod shouldn't cause a nil pointer exception which shuts down the server either. (Maybe just leave the function when [minetest.get_node_or_nil(pos)](https://github.com/Splizard/minetest-mod-snow/blob/master/init.lua#L84) returns nil.)

**Comment by Splizard** [comment]
Fixed 37ecfd02a8d7cf5e0c743e9f9782e9be0551baf8
